import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "../components/navbar";
import { poppins } from "@/lib/font";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Mini blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}, antialiased`}>
        <Navbar />
        <main className="px-6 md:px-0">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
